'use client';

import { ReactNode, RefObject, useEffect, useState } from 'react';
import Link from 'next/link';
import { IconClock, IconFileText, IconMenu, IconSearch, IconUser } from '@/components/ui/Icons';
import { apiFetch } from '@/lib/api';

export function DashboardHeader({ title, description, actions, menuOpen, onOpenMenu, triggerRef }: { title: string; description?: string; actions?: ReactNode; menuOpen: boolean; onOpenMenu: () => void; triggerRef: RefObject<HTMLButtonElement> }) {
  const [online, setOnline] = useState<boolean | null>(null);
  const [query, setQuery] = useState('');
  useEffect(() => { let active = true; const check = async () => { try { const response = await apiFetch('/api/health', { signal: AbortSignal.timeout(4000) }); if (active) setOnline(response.ok); } catch { if (active) setOnline(false); } }; check(); const timer = window.setInterval(check, 30000); return () => { active = false; window.clearInterval(timer); }; }, []);
  return <header className="sticky top-0 z-30 border-b border-white/[0.08] bg-[#080b10]/80 px-4 py-4 backdrop-blur-xl sm:px-6 md:px-8"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><button ref={triggerRef} type="button" onClick={onOpenMenu} className="rounded-xl border border-white/10 p-2 text-slate-400 md:hidden" aria-label="Open dashboard menu" aria-expanded={menuOpen}><IconMenu className="h-5 w-5" /></button><div className="min-w-0"><h1 className="truncate text-xl font-black tracking-tight text-white sm:text-2xl">{title}</h1>{description && <p className="mt-1 truncate text-xs text-slate-500">{description}</p>}</div></div><div className="flex max-w-full flex-wrap items-center justify-end gap-2"><label className="hidden items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-slate-400 lg:flex"><IconSearch className="h-4 w-4" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search archive" className="w-32 bg-transparent text-xs text-white outline-none placeholder:text-slate-600" aria-label="Search archive" /></label><Link href="/vault" className="hidden rounded-xl border border-white/10 p-2 text-slate-400 transition hover:border-cyan-400/40 hover:text-cyan-300 sm:block" aria-label="Open archive"><IconClock className="h-4 w-4" /></Link><Link href="/console" className="hidden rounded-xl border border-white/10 p-2 text-slate-400 transition hover:border-emerald-400/40 hover:text-emerald-300 sm:block" aria-label="Open reports"><IconFileText className="h-4 w-4" /></Link>{actions}<Link href="/settings" className="rounded-xl border border-white/10 p-2 text-slate-300 transition hover:border-cyan-400/40 hover:text-cyan-300" aria-label="Open profile settings"><IconUser className="h-4 w-4" /></Link><span role="status" aria-live="polite" className={`rounded-full border px-3 py-1.5 text-[11px] font-bold ${online === true ? 'border-emerald-400/30 bg-emerald-400/10 text-emerald-100' : online === false ? 'border-rose-400/30 bg-rose-400/10 text-rose-300' : 'border-amber-400/30 bg-amber-400/10 text-amber-300'}`}>{online === true ? 'Online' : online === false ? 'Offline' : 'Connecting'}</span></div></div></header>;
}
